### PR TITLE
package installer and loader

### PR DESCRIPTION
**Pull request by kathryn-willi**
Code to install and load necessary packages for a project, developed by @ccmothes. Can be found in `styleSnippets` folder. 

As I wrote that out, I also noticed that `styleSnippets` is in camelCase. @matthewross07 used to dislike camelCase and preferred snake_case. May want to come up with consistent case structure as part of this style guide.

### CODE REVIEW

**Comment by steeleb** [comment]
YES. I forget that camel case is not tidyverse approved, either. I do it because I'm lazy and hate underscores. Reviewing now!

**Review by steeleb — CHANGES_REQUESTED** [review]
YAS. My only suggestion is that we remove the loop, and then use `lapply()` with the list/function:

```
package_loader <- function(x) {
    if (x %in% installed.packages()) {
      library(x, character.only = TRUE) 
    } else {
      install.packages(x)
      library(x, character.only = TRUE)
    }
}

# fill in with packages that need to be loaded:
packages <- c('tidyverse',
              'sf')

lapply(packages, package_loader)
```
I tried it with `walk()` but then quickly realized that doesn't work because it requires {dplyr}. So {base} `lapply()` it is.

**Comment by steeleb** [comment]
I'm going to change the folder names in my PR!

**Review by kathryn-willi — COMMENTED** [review]
uses `lapply()`

**Pull request merged**
